routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

    Route::prefix('admin')->namespace('Admin')->middleware(['auth:admin'])->group(function(){

            Route::get('/','DashboardController@index')->name('admin.dashboard');

             //admins route
             Route::resource('admins','AdminController')->except(['show']);
        

            //Languages route
            Route::resource('languages','LanguagesController')->except(['show']);
        

            
            //MainCategories route
            Route::resource('maincategories','MainCategoriesController')->except(['show']);

               
            //vendors route
            Route::resource('vendors','VendorController')->except(['show']);
        

        

        });//end of admin routs





Route::group([ 'prefix'=>'admin' , 'namespace'=>'Admin','middleware'=>'guest:admin'] ,function(){
            Route::get('login','loginController@getlogin');
            Route::post('login','loginController@postlogin')->name('admin.login');

        });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/MainCategoriesController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\ModelsAdmin\MainCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Config;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use DB;
use Illuminate\Support\Str;


class MainCategoriesController extends Controller
{

    public function __construct()
    {
            $this->middleware(['permission:maincategories_read'])->only('index');
            $this->middleware(['permission:maincategories_create'])->only('create');
            $this->middleware(['permission:maincategories_update'])->only('edit');
            $this->middleware(['permission:maincategories_delete'])->only('destroy');
    }//end of construct

    public function index()
    {

        $default_lang   = get_default_lang();
        $maincategories = MainCategory::where('translation_lang', $default_lang)
        ->selection()
        ->get();

        return view('admin.maincategories.index',compact('maincategories'));
    }//end of index

   
    public function create()
    {
        return view('admin.maincategories.create');

    }//end of create

  
    public function store(Request $request)
    {
      
        
   
       $request->validate([

    
            'image'             => 'image',
            'category'          => 'required|array|min:1',
            'category.*.name'   => 'required',
            'category.*.abbr'   => 'required',
            'category.*.active' => 'required',

    ]);
         
         try{

            $request_image = $request->except(['image','category','_method','_token']);
        
            $main_catrgory= collect($request->category);

            $filter=$main_catrgory->filter(function($value,$key){
                 
                return $value['abbr']== get_default_lang();
            });//end of filter


             $default_category = array_values ($filter->all())[0];

         
            if ($request->has('image')) {
                Image::make($request->image)
                    ->resize(300, null, function ($constraint) {
                        $constraint->aspectRatio();
                    })
                    ->save(public_path('uploads/category_images/' . $request->image->hashName()));

                    $request_image= $request->image->hashName();
  
        }//end of if

              DB::beginTransaction();
                $default_category_id = MainCategory::insertGetId([
                    'translation_lang' => $default_category['abbr'],
                    'translation_of' => 0,
                    'name' => $default_category['name'],
                    'slug' => $default_category['name'],
                    'image' => $request_image 
                ]); //end of default_category_id


           $categories=$main_catrgory->filter(function($value,$key){
            return $value['abbr'] !== get_default_lang();
        });//enf of categories

      
            if(isset($categories) && $categories->count())
            {
                $categories_arr = [];
                foreach($categories as $category){
                    $categories_arr[] = [
                        'translation_lang' => $category['abbr'],
                        'translation_of'   => $default_category_id ,
                        'name'             => $category['name'],
                        'slug'             => $category['name'],
                         'image'            => $request_image
                    ];
                }//end of foreach

                MainCategory::insert($categories_arr);
            }//end of if 

         DB::commit();
         session()->flash('success', __('site.added_successfully'));
         return redirect()->route('maincategories.index');

        } catch (\Exception $ex) {

            DB::rollback();
            session()->flash('error', __('حدث خطأ لم يتم اضافه البيانات '));
            return redirect()->route('maincategories.index');

        }//en ofcatch
    }//end of store

   

    public function edit(MainCategory $maincategory)
    {
       
        return view('admin.maincategories.edit', compact('maincategory'));

    }//end of edit



    public function update(Request $request, MainCategory $maincategory)
    {
     

       $request->validate([

    
        'image'             => 'image',
        'category'          => 'required|array|min:1',
        'category.*.name'   => 'required|string|min:4',
        'category.*.abbr'   => 'required',
   
        
        ]);//end of validate

        try{

        $request_image = $request->except(['image','category','_method','_token']);

        $request_data = array_values ($request->category)[0];
  
    
        if (!$request->has('category.0.active'))
                $request->request->add(['active' => 0]);
            else
                $request->request->add(['active' => 1]);

               // update data
        $maincategory->update([

                'name'   => $request_data['name'],
                'active' => $request-> active 
               
        ]);//end of update data

            // update image
        if ($request->has('image')){ 

            Storage::disk('public_uploads')->delete('/category_images/' . $maincategory->image);

              }//end of has image

            Image::make($request->image)
                ->resize(300, null, function ($constraint) {
                    $constraint->aspectRatio();
                })
                ->save(public_path('uploads/category_images/' . $request->image->hashName()));

            $request_image= $request->image->hashName();

       

             $maincategory->update([
             'image'  => $request_image
    ]);//end of update image

        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('maincategories.index');

    } catch (\Exception $ex) {

            session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('maincategories.index');

    }//en ofcatch

    }//end of update

    
    public function destroy(MainCategory $maincategory)
    {
        dd($maincategory->id);
        //
    }//end of destory
}

resources/views/admin/maincategories/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                <h3 class="content-header-title">الاقسام الرئيسية</h3>
            
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية </a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('maincategories.index')}}"> الاقسام الرئيسية </a>
                                </li>
                                <li class="breadcrumb-item active">إضافة قسم رئيسي
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic form layout section start -->
                <section id="basic-form-layouts">
                    <div class="row match-height">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title" id="basic-layout-form"> إضافة قسم رئيسي </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                             
                                <div class="card-content collapse show">
                                    <div class="card-body">

                                    @include('partials._errors')

                                        <form class="form" action="{{route('maincategories.store')}}"  method="POST" enctype="multipart/form-data">
                                        {{csrf_field()}}
                                    {{method_field('post')}}

                                        <div class="form-body">
                                                <div class="form-group">
                                                      <label>الصوره</label>
                                                      <input class="form-control image" name="image" type="file" required>
                                                     </div>
                                                                   
                                                     <div class="form-group">
                                                    <img src="{{ asset('uploads/category_images/default.png') }}"  style="width: 100px" class="img-thumbnail image-preview" alt="">
                                                     </div>
                                                     <div class="row">
                                            @if( get_language()->count()> 0 )
                                                @foreach( get_language() as $index => $lang)
                                        
                                                <div class="col-md-6"> 
                                                 <h4 class="form-section"><i class="ft-home"></i> بيانات القسم @lang('site.'.$lang->abbr)</h4>

                                                        <div class="form-group">
                                                            <label for="projectinput1">اسم القسم @lang('site.'.$lang->abbr)</label>
                                                             <input type="text" required id="name" class="form-control" placeholder="@lang('site.'.$lang->direction)" name="category[{{$index}}][name]">    
                                                                </div>
                                                     

                                                        <div class="form-group hidden">
                                                            <label for="projectinput1"> أختصار اللغة @lang('site.'.$lang->abbr)</label>
                                                             <input type="text" id="abbr" class="form-control"   value="{{$lang->abbr}}" name="category[{{$index}}][abbr]">
                                                             </div>

                                                        <div class="form-group mt-1">
                                                            <input type="checkbox"  value="1" name="category[{{$index}}][active]"
                                                                   id="switcheryColor4"
                                                                   class="switchery" data-color="success"
                                                                   checked >
                                                            <label for="switcheryColor4"
                                                                   class="card-title ml-1">الحالة @lang('site.'.$lang->abbr) </label>
                                                        </div>
                                                </div><!--  end of col-md-6 -->
                                        
                                            @endforeach
                                          @endif
                                    </div> <!--  end of row -->  


                                        </div><!-- end of form body -->

                                            <div class="form-actions">
                                                <button type="button" class="btn btn-warning mr-1"
                                                        onclick="history.back();">
                                                    <i class="fas fa-minus-square"></i> تراجع
                                                </button>
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fas fa-plus-square"></i> حفظ
                                                </button>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- // Basic form layout section end -->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/maincategories/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <h3 class="content-header-title"> الاقسام الرئيسية </h3>
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية</a>
                                </li>
                                <li class="breadcrumb-item active"> الاقسام الرئيسية
                                </li>
                            </ol>
                        </div>
                    </div>

                    <br>
                <form action="" method="get" >
                <div class="row">
                <div class="col-md-8">
                    <input class="form-control" name="search" type="text" placeholder="@lang('site.Search')" aria-label="Search" value="{{request()->search}}">
                    </div>
                    <div class="col-md-4">
                    <button class="btn btn-primary" type="submit">@lang('site.Search')<i class="fas fa-search"></i></button>
                    
                    @if(auth()->user()->haspermission('maincategories_create'))     
                    <a href="{{route('maincategories.create')}}" class='btn btn-primary'>@lang('site.add')<i class="fas fa-plus"></i></a>
                    @else
                    <a href="#" class='btn btn-info'>@lang('site.add')<i class="fas fa-plus disabled"></i></a>
                    @endif
                    </div>
                </div>
                </form>

                </div>
            </div>
            <div class="content-body">
                <!-- DOM - jQuery events table -->
                <section id="dom">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">جميع الاقسام الرئيسية </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                                    @if($maincategories->count() > 0 )
                                        <table class="table  table-bordered table-hover">
                                            <thead>
                                            <tr>
                                                <th>القسم </th>
                                                <th> اللغة</th>
                                                <th>الحالة</th>
                                                <th>صوره القسم</th>
                                                <th>الإجراءات</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($maincategories as $category)
                                                    <tr>
                                                        <td>{{$category -> name}}</td>
                                                        <td>{{get_default_lang()}}</td>

                                                       
                                                                <td
                                                                @if($category->active == 1)
                                                                class="btn btn-success btn-sm" 
                                                                @else
                                                                class="btn btn-danger btn-sm" 
                                                                @endif
                                                                style="margin-top: 10px;margin-right: 10px;">

                                                                 {{$category->getActive()}}
                                                                </td>

                            
                                                        <td><img src="{{$category-> image_path }}" style="width: 100px;" class="img-thumbnail" alt=""></td>                                                

                                                        <td>
                                                            <div class="btn-group" role="group"
                                                                 aria-label="Basic example">

                                                                 @if(auth()->user()->haspermission('maincategories_update'))      
                                                                <a href="{{route('maincategories.edit',$category->id)}}"
                                                                class="btn  btn-outline-primary btn-min-width box-shadow-3 mr-1 mb-3 btn-sm "><i class="fa fa-edit" ></i>تعديل</a>
                                                                @else
                                                                <a href="#"
                                                                class="btn btn-outline-info btn-min-width box-shadow-3 mr-1 mb-3 btn-sm disabled"><i class="fa fa-edit" ></i>تعديل</a>
                                                                @endif

                                                                
                                                                @if(auth()->user()->haspermission('maincategories_delete'))     
                                                                <form action="{{route('maincategories.destroy',$category->id)}}"  method="post">
                                                                {{ csrf_field() }}
                                                                {{ method_field('delete')}}
                                                                <button type="submit"  class="btn btn-outline-danger btn-min-width box-shadow-3 mr-1 mb-1 delete btn-sm"><i class="fa fa-trash"></i>@lang('site.delete')</button>
                                
                                                                </form>
                                                                @else
                                                                <button  class="btn btn-outline-danger btn-min-width box-shadow-3 mr-1 mb-3 btn-sm" disabled><i class="fa fa-trash" ></i>@lang('site.delete')</button>
                                                                @endif
                                                      
                                                                @if(auth()->user()->haspermission('maincategories_update'))     
                                                                <a href=""
                                                                   class="btn btn-outline-warning btn-min-width box-shadow-3 mr-1 mb-3 btn-sm">
                                                                   <i class="fa fa-user-slash"></i>
                                                                    @if($category -> active == 0)
                                                                        تفعيل
                                                                        @else
                                                                        الغاء تفعيل
                                                                         @endif
                                                                </a>
                                                                @else
                                                                       
                                                                <a href=""
                                                                   class="btn btn-outline-warning btn-min-width box-shadow-3 mr-1 mb-3 btn-sm disabled">
                                                                   <i class="fa fa-user-slash"></i>
                                                                    @if($category -> active == 0)
                                                                        تفعيل
                                                                        @else
                                                                        الغاء تفعيل
                                                                         @endif
                                                                </a>
                                                                @endif
                                                            </div>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                        

                                            </tbody>
                                        </table>
                        
                                   @else
                                  <h2>@lang('site.no_deta_found')</h2>
                                  @endif
                                        <div class="justify-content-center d-flex">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection