routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

    Route::prefix('admin')->namespace('Admin')->middleware(['auth:admin'])->group(function(){

            Route::get('/','DashboardController@index')->name('admin.dashboard');

             //admins route
             Route::resource('admins','AdminController')->except(['show']);
        

            //Languages route
            Route::resource('languages','LanguagesController')->except(['show']);
        

            
            //MainCategories route
            Route::resource('maincategories','MainCategoriesController')->except(['show']);

               
            //vendors route
            Route::resource('vendors','VendorController')->except(['show']);
        

        

        });//end of admin routs





Route::group([ 'prefix'=>'admin' , 'namespace'=>'Admin','middleware'=>'guest:admin'] ,function(){
            Route::get('login','loginController@getlogin');
            Route::post('login','loginController@postlogin')->name('admin.login');

        });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/LanguagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\ModelsAdmin\Language;
use Illuminate\Http\Request;

class LanguagesController extends Controller
{
    public function __construct()
    {
            $this->middleware(['permission:languages_read'])->only('index');
            $this->middleware(['permission:languages_create'])->only('create');
            $this->middleware(['permission:languages_update'])->only('edit');
            $this->middleware(['permission:languages_delete'])->only('destroy');
    }//end of construct 

   
    public function index(Request $request)

    {

        $languages = Language::when($request->search,function($q) use ($request){

            return $q->where('name','like','%' .$request->search .'%')
            ->orwhere('abbr','like','%' .$request->search .'%');

        })->latest()->paginate(5);
        return view('admin.languages.index',compact('languages'));
    }//end of index 

    public function create()
    {
        return view('admin.languages.create');

    }//end of create 

    
    public function store(Request $request)
    {
            // dd($request->all());
            $request->validate([
            
                'name' => 'required|string|max:100',
                'abbr' => 'required|string|max:10',
                'active' => 'required|in:1',
                'direction' => 'required|in:rtl,ltr',

            ]);

            Language::create($request->all());
            
            session()->flash('success', __('site.added_successfully'));
            return redirect()->route('languages.index');

    }//end of store 

    public function edit(Language $language)
    {
        return view('admin.languages.edit',compact('language'));

    }//end of edit 

 
    public function update(Request $request, Language $language)
    {
                 
        $request->validate([

            'name' => 'required|string|max:100',
            'abbr' => 'required|string|max:10',
            'direction' => 'required|in:rtl,ltr',


        ]);//end of validate

        if (!$request->has('active'))
        $request->request->add(['active' => 0]);


        $language->update($request->all());
        session()->flash('success', __('site.updated_successfully'));
        return redirect()->route('languages.index');
        
    }//end of update 
    


    public function destroy(Language $language)
    {
        $language->delete();
        session()->flash('success', __('site.deleted_successfully'));
        return redirect()->route('languages.index');

    }//end of destroy 

}//end of LanguagesController 

resources/views/admin/languages/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                
                <h3 class="content-header-title"> اللغات </h3>
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية </a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('languages.index')}}"> اللغات </a>
                                </li>
                                <li class="breadcrumb-item active">إضافة لغة
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic form layout section start -->
                <section id="basic-form-layouts">
                    <div class="row match-height">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title" id="basic-layout-form"> إضافة لغة </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body">

                                    @include('partials._errors')

                                        <form class="form" action="{{route('languages.store')}}" method="POST"
                                              enctype="multipart/form-data">
                                            
                                      {{csrf_field()}}
                                    {{method_field('post')}}

                                            <div class="form-body">
                                                <h4 class="form-section"><i class="ft-home"></i> بيانات  اللغة </h4>

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="projectinput1"> اسم اللغة </label>
                                                            <input type="text" value="" id="name"
                                                                   class="form-control"
                                                                   placeholder="ادخل اسم اللغة  "
                                                                   name="name">
                                                
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="projectinput1"> أختصار اللغة </label>
                                                            <input type="text" value="" id="name"
                                                                   class="form-control"
                                                                   placeholder="ادخل أختصار اللغة  "
                                                                   name="abbr">
                                                           
                                                        </div>
                                                    </div>
                                                </div>



                                                <div class="row">

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="projectinput2"> الاتجاة </label>
                                                            <select name="direction" class="select2 form-control">
                                                                <optgroup label="من فضلك أختر اتجاه اللغة ">
                                                                    <option value="rtl">من اليمين الي اليسار</option>
                                                                    <option value="ltr">من اليسار الي اليمين</option>
                                                                </optgroup>
                                                            </select>
                                                
                                                        </div>
                                                    </div>
                                                </div>


                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group mt-1">
                                                            <input type="checkbox"  value="1" name="active"
                                                                   id="switcheryColor4"
                                                                   class="switchery" data-color="success"
                                                                   checked/>
                                                            <label for="switcheryColor4"
                                                                   class="card-title ml-1">الحالة </label>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-actions">
                                                <button type="button" class="btn btn-warning mr-1"
                                                        onclick="history.back();">
                                                    <i class="fas fa-minus-square"></i> تراجع
                                                </button>
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fas fa-plus-square"></i> حفظ
                                                </button>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- // Basic form layout section end -->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/languages/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية </a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('languages.index')}}"> أللغات </a>
                                </li>
                                <li class="breadcrumb-item active">تعديل لغة
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic form layout section start -->
                <section id="basic-form-layouts">
                    <div class="row match-height">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title" id="basic-layout-form"> إضافة لغة </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            
                                <div class="card-content collapse show">
                                    <div class="card-body">
                                    @include('partials._errors')
                                        <form class="form" action="{{route('languages.update',$language -> id)}}" method="POST"
                                              enctype="multipart/form-data">
                                              {{csrf_field()}}
                                            {{method_field('put')}}
                                            <div class="form-body">
                                                <h4 class="form-section"><i class="ft-home"></i> بيانات  اللغة </h4>

                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="projectinput1"> اسم اللغة </label>
                                                            <input type="text"  id="name"
                                                                   class="form-control"
                                                                   value="{{$language -> name}}"
                                                                   placeholder="ادخل اسم اللغة  "
                                                                   name="name">
                                                        
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="projectinput1"> أختصار اللغة </label>
                                                            <input type="text" value="{{$language -> abbr}}" id="name"
                                                                   class="form-control"
                                                                   placeholder="ادخل أختصار اللغة  "
                                                                   name="abbr">
                                                            
                                                        </div>
                                                    </div>
                                                </div>



                                                <div class="row">

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="projectinput2"> الاتجاة </label>
                                                            <select name="direction" class="select2 form-control">
                                                                <optgroup label="من فضلك أختر اتجاه اللغة ">
                                                                    <option value="rtl" @if($language ->direction == 'rtl' ) selected @endif>من اليمين الي اليسار</option>
                                                                    <option value="ltr" @if($language ->direction == 'ltr') selected @endif>من اليسار الي اليمين</option>
                                                                </optgroup>
                                                            </select>
                                                       
                                                        </div>
                                                    </div>
                                                </div>


                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group mt-1">
                                                            <input type="checkbox"  value="1" name="active"
                                                                   id="switcheryColor4"
                                                                   class="switchery" data-color="success"

                                                                  @if($language -> active  == 1 ) checked @endif
                                                            />
                                                            <label for="switcheryColor4"
                                                                   class="card-title ml-1">الحالة </label>

                                                           
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                            <div class="form-actions">
                                                <button type="button" class="btn btn-warning mr-1"
                                                        onclick="history.back();">
                                                    <i class="fas fa-minus-square"></i> تراجع
                                                </button>
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fas fa-edit"></i> تعديل
                                                </button>

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- // Basic form layout section end -->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/languages/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">

                    <h3 class="content-header-title"> اللغات <small>{{$languages->total()}}</small> </h3>

                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية</a>
                                </li>
                                <li class="breadcrumb-item active"> اللغات
                                </li>
                            </ol>
                        </div>
                    </div>
                    <br>
                <form action="" method="get" >
                <div class="row">
                <div class="col-md-8">
                    <input class="form-control" name="search" type="text" placeholder="@lang('site.Search')" aria-label="Search" value="{{request()->search}}">
                    </div>
                    <div class="col-md-4">
                    <button class="btn btn-primary" type="submit">@lang('site.Search')<i class="fas fa-search"></i></button>
                    
                    @if(auth()->user()->haspermission('languages_create'))     
                    <a href="{{route('languages.create')}}" class='btn btn-primary'>@lang('site.add')<i class="fas fa-plus"></i></a>
                    @else
                    <a href="#" class='btn btn-info'>@lang('site.add')<i class="fas fa-plus disabled"></i></a>
                    @endif
                    </div>
                </div>
                </form>
                
                </div>
            </div>
            
            <div class="content-body">
                <!-- DOM - jQuery events table -->
                <section id="dom">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">جميع لغات الموقع </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>

                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                        
                                    @if($languages->count() > 0 )

                                        <table
                                            class="table display nowrap table-striped table-bordered ">
                                            <thead>
                                            <tr>
                                                <th> الاسم</th>
                                                <th>الاختصار</th>
                                                <th>اتجاه</th>
                                                <th>الحالة</th>
                                                <th>الإجراءات</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($languages as $language)
                                                    <tr>
                                                        <td>{{$language -> name}}</td>
                                                        <td>{{$language -> abbr}}</td>
                                                        <td>{{$language -> direction}}</td>
                                                        <td>{{$language -> getActive()}}</td>
                                                        <td>
                                                            <div class="btn-group" role="group"
                                                                 aria-label="Basic example">
                                                         @if(auth()->user()->haspermission('languages_update'))   
                                                         <a href="{{route('languages.edit',$language->id)}}"
                                                         class="btn btn-outline-primary btn-min-width box-shadow-3 mr-1 mb-1 btn-sm"><i class="fa fa-edit" ></i> تعديل</a>
                                                        @else
                                                         <a href="#"
                                                         class="btn btn-outline-primary btn-min-width box-shadow-3 mr-1 mb-1 btn-sm disabled"> <i class="fa fa-edit" ></i> تعديل</a>
                                                        @endif
                                                        
                                                        @if(auth()->user()->haspermission('languages_delete'))   
                                                         <form action="{{route('languages.destroy',$language->id)}}"  method="post">
                                                        {{ csrf_field() }}
                                                        {{ method_field('delete')}}
                                                        <button type="submit"  class="btn btn-outline-danger btn-min-width box-shadow-3 mr-1 mb-1 delete btn-sm"><i class="fa fa-trash" ></i>@lang('site.delete')</button>
                                                         </form>
                                                         @else
                                                         <button  class="btn btn-outline-danger btn-min-width box-shadow-3 mr-1 mb-1 delete btn-sm" disabled><i class="fa fa-trash" ></i>@lang('site.delete')</button>
                                                         @endif

                                                            </div>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                        {{$languages->appends(request()->query())->links()}}
                                   
                                     @else
                                    <h2>@lang('site.no_deta_found')</h2>
                                    @endif
                                        <div class="justify-content-center d-flex">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection