routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

    Route::prefix('admin')->namespace('Admin')->middleware(['auth:admin'])->group(function(){

            Route::get('/','DashboardController@index')->name('admin.dashboard');

             //admins route
             Route::resource('admins','AdminController')->except(['show']);
        

            //Languages route
            Route::resource('languages','LanguagesController')->except(['show']);
        

            
            //MainCategories route
            Route::resource('maincategories','MainCategoriesController')->except(['show']);

               
            //vendors route
            Route::resource('vendors','VendorController')->except(['show']);
        

        

        });//end of admin routs





Route::group([ 'prefix'=>'admin' , 'namespace'=>'Admin','middleware'=>'guest:admin'] ,function(){
            Route::get('login','loginController@getlogin');
            Route::post('login','loginController@postlogin')->name('admin.login');

        });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/admins/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                
                <h3 class="content-header-title"> المشرفين </h3>
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية </a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('admins.index')}}"> المشرفين </a>
                                </li>
                                <li class="breadcrumb-item active">إضافة مشرف
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic form layout section start -->
                <section id="basic-form-layouts">
                    <div class="row match-height">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title" id="basic-layout-form"> إضافة مشرف </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                             
                                <div class="card-content collapse show">
                                    <div class="card-body">

                                    @include('partials._errors')

                                        <form class="form" action="{{route('admins.store')}}" method="POST"
                                              enctype="multipart/form-data">
                                            
                                      {{csrf_field()}}
                                    {{method_field('post')}}

                                    <div class="form-body">
                                     <h4 class="form-section"><i class="ft-home"></i> بيانات  المشرفين </h4>
                                      <div class="row">

                                         <div class="col-md-12">
                                          <div class="form-group">
                                            <label for="projectinput1">الاسم الاول</label>
                                               <input type="text" value="{{old('first_name')}}" id="first_name" class="form-control" placeholder="الاسم الاول" name="first_name" required>                                               
                                                </div>
                                                </div>

                                                
                                         <div class="col-md-12">
                                          <div class="form-group">
                                            <label for="projectinput1">الاسم الاخير</label>
                                               <input type="text" value="{{old('last_name')}}" id="last_name" class="form-control" placeholder="الاسم الاخير" name="last_name" required>                                               
                                                </div>
                                                </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
    
                                                            <label for="projectinput1">البريد الاكترونى</label>
                                                            <input type="email" value="{{old('email')}}" id="email"
                                                                   class="form-control"
                                                                   placeholder="ادخل  البريد الالكترونى  "
                                                                   name="email" required>
                                                           
                                                        </div>
                                                    </div>
                                                </div>

                                                                            
                                                  <div class="form-group">
                                                      <label>@lang('site.image')</label>
                                                      <input class="form-control image" name="image" type="file" required>
                                                  </div>

                                                                            
                                                  <div class="form-group">
                                                    <img src="{{ asset('uploads/admins_images/default.png') }}"  style="width: 100px" class="img-thumbnail image-preview" alt="">
                                                </div>



                                                <div class="row">
                                                    <div class="col-md-12">
                                                    <div class="form-group">
            
                                                    <label for="projectinput1">كلمه المرور</label>
                                                    <input type="password" value="{{old('password')}}" id="password"
                                                          class="form-control"
                                                          placeholder="ادخل  كلمه المرور  "
                                                          name="password" required>
                                                  
                                                    </div>
                                                    </div>
                                                </div>

                                                
                                                <div class="row">
                                                    <div class="col-md-12">
                                                    <div class="form-group">
          
                                                    <label for="projectinput1"> تاكيد كلمه المرور </label>
                                                    <input type="password" value="{{old('password_confirmation')}}" id="password"
                                                          class="form-control"
                                                          placeholder="ادخل تاكيد كلمه المرور "
                                                          name="password_confirmation" required>
                                                  
                                                </div>
                                                    </div>
                                                </div>


                                                <div class="form-group">
                                      <label style="margin-bottom: 15px;">@lang('site.permissions')</label>

                                    @php

                                        $models = ['admins','maincategories','vendors','languages'];
                                        $crud   = ['create','read','update','delete']

                                    @endphp

                             <div class="box">
                            <div class="box d-flex p-0">
                              <ul class="nav nav-tabs active" style=" margin-left: 71%;">
                              @foreach($models as $index => $model)
                              <li class="nav-item"><a class="nav-link {{$index == 0 ? 'active' : '' }}" href="#{{$model}}" data-toggle="tab"> @lang('site.' .$model)</a></li>
                              @endforeach
                              </ul>
                            

                            </div><!-- /.card-header -->  
                            <div class="card-body">
                              <div class="tab-content">

                                @foreach($models as $index => $model)

                                <div class="tab-pane {{$index == 0 ? 'active' : '' }}" id="{{$model}}">

                                @foreach($crud as $prem)

                                <input  name="permissions[]" type="checkbox"  value="{{$model. '_' .$prem  }}"> <label style="margin-left: 10px;"> @lang('site.' .$prem) </label>
                                @endforeach                           
                                </div>
                                @endforeach
                          
                              </div>
                              <!-- /.tab-content -->
                            </div><!-- /.card-body -->
                          </div>


                                      </div>


                                      <div class="form-actions">
                                                <button type="button" class="btn btn-warning mr-1"
                                                        onclick="history.back();">
                                                    <i class="fas fa-minus-square"></i> تراجع
                                                </button>
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fas fa-plus-square"></i> حفظ
                                                </button>
                                            </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- // Basic form layout section end -->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/admins/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                
                <h3 class="content-header-title"> المشرفين </h3>
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية </a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('admins.index')}}"> المشرفين </a>
                                </li>
                                <li class="breadcrumb-item active">تعديل مشرف
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic form layout section start -->
                <section id="basic-form-layouts">
                    <div class="row match-height">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title" id="basic-layout-form"> تعديل مشرف </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                             
                                <div class="card-content collapse show">
                                    <div class="card-body">

                                    @include('partials._errors')

                                        <form class="form" action="{{route('admins.update',$admin->id)}}" method="POST"
                                              enctype="multipart/form-data">
                                            
                                      {{csrf_field()}}
                                    {{method_field('put')}}

                                    <div class="form-body">
                                     <h4 class="form-section"><i class="ft-home"></i> بيانات  المشرفين </h4>
                                      <div class="row">

                                         <div class="col-md-12">
                                          <div class="form-group">
                                            <label for="projectinput1">الاسم الاول</label>
                                               <input type="text" value="{{$admin->first_name}}" id="first_name" class="form-control" placeholder="الاسم الاول" name="first_name">                                               
                                                </div>
                                                </div>

                                                
                                         <div class="col-md-12">
                                          <div class="form-group">
                                            <label for="projectinput1">الاسم الاخير</label>
                                               <input type="text" value="{{$admin->last_name}}" id="last_name" class="form-control" placeholder="الاسم الاخير" name="last_name">                                               
                                                </div>
                                                </div>

                                                    <div class="col-md-12">
                                                        <div class="form-group">
    
                                                            <label for="projectinput1">البريد الاكترونى</label>
                                                            <input type="email" value="{{$admin->email}}" id="email"
                                                                   class="form-control"
                                                                   placeholder="ادخل  البريد الالكترونى  "
                                                                   name="email">
                                                           
                                                        </div>
                                                    </div>
                                                </div>

                                                                            
                                                  <div class="form-group">
                                                      <label>@lang('site.image')</label>
                                                      <input class="form-control image" name="image" type="file">
                                                  </div>

                                                                            
                                                  <div class="form-group">
                                                    <img src="{{$admin-> image_path }}"  style="width: 100px" class="img-thumbnail image-preview" alt="">
                                            
                                                    </div>
                                                </div>


                                                <div class="form-group">
                                      <label style="margin-bottom: 15px;">@lang('site.permissions')</label>

                                    @php

                                        $models = ['admins','maincategories','vendors','languages'];
                                        $crud   = ['create','read','update','delete']

                                    @endphp

                                      <div class="card">
                            <div class="card d-flex p-0">
                              <ul class="nav nav-tabs active" style=" margin-left: 71%;">
                              @foreach($models as $index => $model)
                              <li class="nav-item"><a class="nav-link {{$index == 0 ? 'active' : '' }}" href="#{{$model}}" data-toggle="tab">@lang('site.' .$model)</a></li>
                              @endforeach
                              </ul>
                            

                            </div><!-- /.card-header -->  
                            <div class="card-body">
                              <div class="tab-content">

                                @foreach($models as $index => $model)

                                <div class="tab-pane {{$index == 0 ? 'active' : '' }}" id="{{$model}}">

                                @foreach($crud as $prem)
                                <input name="permissions[]" type="checkbox" {{$admin->haspermission($model. '_' .$prem ) ? 'checked' : ''}}  value="{{$model. '_' .$prem  }}"> <label style="margin-left: 10px;"> @lang('site.' .$prem) </label>

                                @endforeach                           
                                </div>
                                @endforeach
                          
                              </div>
                              <!-- /.tab-content -->
                            </div><!-- /.card-body -->
                          </div>


                                      </div>
                                      <div class="form-actions">
                                                <button type="button" class="btn btn-warning mr-1"
                                                        onclick="history.back();">
                                                    <i class="fas fa-minus-square"></i> تراجع
                                                </button>
                                                <button type="submit" class="btn btn-primary">
                                                    <i class="fas fa-edit"></i> تعديل
                                                </button>
                        
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- // Basic form layout section end -->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/admins/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">

                    <h3 class="content-header-title"> المشرفين <small>{{$admins->total()}}</small> </h3>

                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">الرئيسية</a>
                                </li>
                                <li class="breadcrumb-item active"> المشرفين
                                </li>
                            </ol>
                        </div>
                    </div>
                    <br>
                <form action="" method="get" >
                <div class="row">
                <div class="col-md-8">
                    <input class="form-control" name="search" type="text" placeholder="@lang('site.Search')" aria-label="Search" value="{{request()->search}}">
                    </div>
                    <div class="col-md-4">
                    <button class="btn btn-primary" type="submit">@lang('site.Search')<i class="fas fa-search"></i></button>
                    @if(auth()->user()->haspermission('admins_create'))
                    <a href="{{route('admins.create')}}" class='btn btn-primary'>@lang('site.add')<i class="fas fa-plus"></i></a>
                    @else
                    <a href="#" class='btn btn-info disabled'>@lang('site.add')<i class="fas fa-plus"></i></a>
                    @endif
                    </div>
                </div>
                </form>
                </div>
            </div>
            
            <div class="content-body">
                <!-- DOM - jQuery events table -->
                <section id="dom">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">جميع مشرفين الموقع </h4>
                                    <a class="heading-elements-toggle"><i
                                            class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>

                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                        
                                    @if($admins->count() > 0 )

                                        <table
                                            class="table display nowrap table-striped table-bordered ">
                                            <thead>
                                            <tr>
                                                <th>الاسم الاول</th>
                                                <th>الاسم الاخير</th>
                                                <th>البريد الاكترونى</th>
                                                <th>الصوره</th>
                                                <th>الإجراءات</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($admins as $admin)
                                                    <tr>
                                                        <td>{{$admin -> first_name}}</td>
                                                        <td>{{$admin -> last_name}}</td>
                                                        <td>{{$admin -> email}}</td>
                                                        <td><img src="{{$admin-> image_path }}" style="width: 100px;" class="img-thumbnail" alt=""></td>                                                
                                                        <td>
                                                            <div class="btn-group" role="group"
                                                                 aria-label="Basic example">
                                                                 
                                                         @if(auth()->user()->haspermission('admins_update'))      
                                                         <a href="{{route('admins.edit',$admin->id)}}"
                                                         class="btn btn-outline-primary btn-min-width box-shadow-3 mr-1 mb-1 btn-sm"> <i class="fa fa-user-edit" ></i> تعديل</a>
                                                         @else
                                                         <a href="#"
                                                         class="btn btn-outline-info btn-min-width box-shadow-3 mr-1 mb-1 btn-sm disabled"> <i class="fa fa-user-edit" ></i> تعديل</a>
                                                        @endif

                                                        @if(auth()->user()->haspermission('admins_delete'))     
                                                         <form action="{{route('admins.destroy',$admin->id)}}"  method="post">
                                                        {{ csrf_field() }}
                                                        {{ method_field('delete')}}
                                                        <button type="submit"  class="btn btn-outline-danger btn-min-width box-shadow-3 mr-1 mb-1 delete btn-sm"><i class="fa fa-trash" ></i>@lang('site.delete')</button>
                        
                                                        </form>
                                                        @else
                                                        <button  class="btn btn-outline-danger btn-min-width box-shadow-3 mr-1 mb-1 btn-sm" disabled><i class="fa fa-trash" ></i>@lang('site.delete')</button>
                                                        @endif
                                                      

                                                            </div>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                        {{$admins->appends(request()->query())->links()}}
                                   
                                     @else
                                    <h2>@lang('site.no_deta_found')</h2>
                                    @endif
                                        <div class="justify-content-center d-flex">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection