routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

    Route::prefix('admin')->namespace('Admin')->middleware(['auth:admin'])->group(function(){

            Route::get('/','DashboardController@index')->name('admin.dashboard');

             //admins route
             Route::resource('admins','AdminController')->except(['show']);
        

            //Languages route
            Route::resource('languages','LanguagesController')->except(['show']);
        

            
            //MainCategories route
            Route::resource('maincategories','MainCategoriesController')->except(['show']);

               
            //vendors route
            Route::resource('vendors','VendorController')->except(['show']);
        

        

        });//end of admin routs





Route::group([ 'prefix'=>'admin' , 'namespace'=>'Admin','middleware'=>'guest:admin'] ,function(){
            Route::get('login','loginController@getlogin');
            Route::post('login','loginController@postlogin')->name('admin.login');

        });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/includes/footer.blade.php
<footer class="footer footer-static footer-light navbar-border navbar-shadow">
    <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
      <span class="float-md-left d-block d-md-inline-block">Copyright &copy; {{date('Y')}} <a class="text-bold-800 grey darken-2" href=""
                                                                                     target="_blank">Ahmed Emam </a>, All rights reserved. </span>
        <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block"> done <i class="ft-heart pink"></i></span>
    </p>
</footer>

resources/views/admin/includes/sidebar.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion   menu-shadow " data-scroll-to-active="true">

    <div class="main-menu-content">

        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

              <!-- الرئيسية -->
            <li class="nav-item">

              <a href=""><i class="la la-mouse-pointer"></i>

               <span class="menu-title" data-i18n="nav.add_on_drag_drop.main">الرئيسية </span>

              </a>

            </li><!--end of li nav-item   --> 



            @if(auth()->user()->haspermission('maincategories_read'))
              <!-- الاقسام الرثيسيه  -->
             <li class="nav-item">
                    <a href="{{route('maincategories.index')}}"><i class="la la-home"></i>
                        <span class="menu-title" data-i18n="nav.dash.main"> الاقسام الرئيسية </span>
                        <span class="badge badge badge-info badge-pill float-right mr-2">{{App\ModelsAdmin\MainCategory::count()}}</span>
                    </a>
             </li><!--end of li nav-item   --> 
             @endif


             @if(auth()->user()->haspermission('vendors_read'))
              <!-- المتاجر   -->
             <li class="nav-item">
                    <a href="{{route('vendors.index')}}"><i class="la la-home"></i>
                        <span class="menu-title" data-i18n="nav.dash.main"> المتاجر </span>
                        <span class="badge badge badge-info badge-pill float-right mr-2">{{App\ModelsAdmin\Vendor::count()}}</span>
                    </a>
             </li><!--end of li nav-item   --> 
             @endif


             @if(auth()->user()->haspermission('languages_read'))
              <!-- لغات الموقع -->
            <li class="nav-item">

                <a href="{{route('languages.index')}}"><i class="la la-home"></i>

                    <span class="menu-title" data-i18n="nav.dash.main">لغات الموقع </span>
                    <span class="badge badge badge-info badge-pill float-right mr-2">{{App\ModelsAdmin\Language::count()}}</span>
               </a>
               
            </li><!--end of li nav-item   -->
            @endif


            @if(auth()->user()->haspermission('admins_read'))
              <!-- المشرفين -->
              <li class="nav-item">
          <a href="{{route('admins.index')}}"><i class="la la-home"></i>
              <span class="menu-title" data-i18n="nav.dash.main">المشرفين</span>
              <span class="badge badge badge-info badge-pill float-right mr-2">{{App\ModelsAdmin\Admin::whereRoleIs('admin')->count()}}</span>
          </a>
          </li><!--end of li nav-item   --> 
          @endif

        </ul><!--end of ul navigation --> 

    </div><!--end of content --> 

 </div><!--end of main-menu --> 